# Generated by Django 4.2 on 2024-10-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('warehouse', models.CharField()),
                ('rent_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent_paid', models.FloatField()),
                ('note', models.TextField(null=True)),
            ],
        ),
    ]
